kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amazing-anupam-admin
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]